apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbsg-ai-rfp-assistant
  labels:
    app: tbsg-ai-rfp-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tbsg-ai-rfp-assistant
  template:
    metadata:
      labels:
        app: tbsg-ai-rfp-assistant
    spec:
      containers:
      - name: tbsg-ai-rfp-assistant
        image: ghcr.io/georgasa/tbsg-ai-rfp-assistant:latest
        ports:
        - containerPort: 5000
        env:
        - name: TEMENOS_JWT_TOKEN
          valueFrom:
            secretKeyRef:
              name: temenos-secrets
              key: jwt-token
        - name: DEMO_MODE
          value: "false"
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tbsg-ai-rfp-assistant-service
spec:
  selector:
    app: tbsg-ai-rfp-assistant
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer




