apiVersion: apps/v1
kind: ContainerApp
metadata:
  name: tbsg-ai-rfp-assistant
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: tbsg-ai-rfp-assistant
    spec:
      containers:
      - name: tbsg-ai-rfp-assistant
        image: ghcr.io/georgasa/tbsg-ai-rfp-assistant:latest
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: TEMENOS_JWT_TOKEN
          secretRef: temenos-jwt-token
        - name: DEMO_MODE
          value: "false"
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: 0.25
            memory: 0.5Gi
          limits:
            cpu: 0.5
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /api/test-connection
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/test-connection
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: tbsg-ai-rfp-assistant
  service:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
